import assert from 'node:assert';
import {
  parsePrintTimeString,
  formatPrintTime,
  colorDistance,
  matchFilamentToRoll,
  parseGcodeText,
} from '../src/lib/gcodeParser.js';

console.log('--- Testing G-Code Parser & Auto-Matcher ---');

// Test 1: Time parsing
assert.strictEqual(parsePrintTimeString('2h 15m 30s'), 8130);
assert.strictEqual(parsePrintTimeString('45m'), 2700);
assert.strictEqual(formatPrintTime(8130), '2h 15m');
assert.strictEqual(formatPrintTime(1800), '30m');
console.log('✓ Test 1: Print time parsing and formatting verified');

// Test 2: Color distance
const blackDist = colorDistance('#000000', '#1f2023');
const whiteDist = colorDistance('#000000', '#ffffff');
assert(blackDist < 60, 'Black to dark gray should have low distance');
assert(whiteDist > 400, 'Black to white should have near max distance');
console.log('✓ Test 2: RGB color distance verified');

// Test 3: Single extrusion G-code parse
const gcodeSingle = `
; generated by Anycubic Slicer Next 1.4.3
; filament used [g] = 28.5
; filament_type = PLA
; filament_colour = #1f2023
; estimated printing time (normal mode) = 1h 45m 12s
`;

const rolls = [
  {
    id: 'roll-black',
    brand: 'Bambu Lab',
    material: 'PLA',
    colorName: 'Negro carbón',
    colorHex: '#1f2023',
    remainingWeight: 500,
    status: 'in_use',
  },
  {
    id: 'roll-orange',
    brand: 'Elegoo',
    material: 'PLA',
    colorName: 'Naranja fuego',
    colorHex: '#f0731d',
    remainingWeight: 300,
    status: 'in_use',
  },
];

const jobSingle = parseGcodeText(gcodeSingle, 'soporte_auriculares.gcode', '', rolls);
assert.strictEqual(jobSingle.filename, 'soporte_auriculares');
assert.strictEqual(jobSingle.totalGrams, 28.5);
assert.strictEqual(jobSingle.printTimeSeconds, 6312);
assert.strictEqual(jobSingle.filaments.length, 1);
assert.strictEqual(jobSingle.filaments[0].rollId, 'roll-black', 'Should auto-match to the black PLA spool');
console.log('✓ Test 3: Single extrusion parsed and correctly matched to roll-black');

// Test 4: Multicolor G-code parse
const gcodeMulti = `
; generated by Anycubic Slicer Next 1.4.3
; filament used [g] = 12.4, 35.8
; filament_type = PLA;PLA
; filament_colour = #1f2023;#f0731d
; estimated printing time (normal mode) = 3h 10m
`;

const jobMulti = parseGcodeText(gcodeMulti, 'figura_bicolor.gcode.3mf', '', rolls);
assert.strictEqual(jobMulti.filaments.length, 2);
assert.strictEqual(jobMulti.filaments[0].grams, 12.4);
assert.strictEqual(jobMulti.filaments[0].rollId, 'roll-black');
assert.strictEqual(jobMulti.filaments[1].grams, 35.8);
assert.strictEqual(jobMulti.filaments[1].rollId, 'roll-orange');
assert.strictEqual(jobMulti.totalGrams, 48.2);
console.log('✓ Test 4: Multicolor extrusion parsed and matched both filaments');

console.log('ALL G-CODE TESTS PASSED!');
